
version: build{build}
image: Visual Studio 2017
clone_folder: C:\CK-World\CK-Database-Projects\CK-DB-GitHub
services: mssql2016
branches:
  only:
    - master
    - develop
environment:
  SqlServer/MasterConnectionString: Server=(local)\SQL2016;Database=master;User ID=sa;Password=Password12!
  CODECAKEBUILDER_SECRET_KEY:
    secure: ks+QpMhDl8xJnpAmU4OHdfh11TE+fwNBj4PvMAKrPGsJnNjXcKgXtgAyJo77SJBi
artifacts:
  - path: Tests/CK.DB.User.UserGitHub.Tests/Logs
  - path: Tests/CK.DB.User.UserGitHub.AuthScope.Tests/Logs
build_script:
  - dotnet run --project CodeCakeBuilder -nointeraction
test: off
install: 'ps: ./CodeCakeBuilder/InstallCredentialProvider.ps1'
